# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('start_estimated', models.DateField()),
                ('end_estimated', models.DateField()),
                ('state', models.CharField(choices=[('on', 'Em Andamento'), ('end', 'Conclu\xeddo'), ('off', 'Cancelado/Arquivado')], default='on', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_ended', models.IntegerField(default=0)),
                ('act_program', models.IntegerField(default=0)),
                ('act_late', models.IntegerField(default=0)),
                ('act_total', models.IntegerField(default=0)),
                ('deliveried', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'ProjectStatus',
            },
        ),
    ]
