# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-30 18:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('on', 'Programado'), ('end', 'Conclu\xeddo'), ('wip', 'Em Andamento')], default='on', max_length=3)),
                ('duration_estimated', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_estimated', models.DateField()),
                ('end_estimated', models.DateField()),
                ('data_center', models.CharField(choices=[('Norte', 'Norte'), ('Sul', 'Sul')], default='Norte', max_length=8)),
                ('local', models.CharField(default='na', max_length=15)),
                ('start_real', models.DateField(blank=True, null=True)),
                ('end_real', models.DateField(blank=True, null=True)),
                ('duration_real', models.IntegerField(blank=True, null=True)),
                ('late', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
